### ISSUE TITLE
problem in compiling

### ISSUE THREAD

**Issue by lmanchon** [dancooke/tandem#1]
--Hi,

i use gcc-4.9.1 and i think c++14 support is not available:

g++ example.cpp tandem.cpp libdivsufsort/divsufsort.c libdivsufsort/sssort.c libdivsufsort/trsort.c libdivsufsort/utils.c -w -std=c++14 -O3 -o tandem
In file included from tandem.hpp:41:0,
                 from example.cpp:10:
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:74:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:86:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:94:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:108:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:123:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:137:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:152:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
libdivsufsort/divsufsort.h:40:36: error: expected constructor, destructor, or type conversion before ‘(’ token
 #  define DIVSUFSORT_API __declspec(dllimport)
                                    ^
libdivsufsort/divsufsort.h:169:1: note: in expansion of macro ‘DIVSUFSORT_API’
 DIVSUFSORT_API
 ^
In file included from example.cpp:10:0:
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&)’:
tandem.hpp:86:35: error: ‘cbegin’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                   ^
tandem.hpp:86:52: error: ‘cend’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                                    ^
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&, size_t)’:
tandem.hpp:98:31: error: ‘cbegin’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                               ^
tandem.hpp:98:48: error: ‘cend’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                                                ^
tandem.hpp: In function ‘uint32_t Tandem::detail::forward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:118:20: error: ‘std::cbegin’ has not been declared
         using std::cbegin;
                    ^
tandem.hpp: In function ‘uint32_t Tandem::detail::backward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:133:20: error: ‘std::crend’ has not been declared
         using std::crend;
                    ^
tandem.hpp: In function ‘std::vectorstd::vector<Tandem::StringRun > Tandem::detail::get_end_buckets(const T&, const std::vectorTandem::LZBlock&, uint32_t, uint32_t)’:
..../...

**Comment by dancooke** [comment]
This was a problem with the __declspec libdivsudsort used. I've removed it and the example should now compile.
