### ISSUE TITLE
again compilation problem

### ISSUE THREAD

**Issue by lmanchon** [dancooke/tandem#2]
-- sorry but it failed again:

g++ example.cpp tandem.cpp libdivsufsort/divsufsort.c libdivsufsort/sssort.c libdivsufsort/trsort.c libdivsufsort/utils.c -w -std=c++14 -O3 -o tandem
In file included from example.cpp:10:0:
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&)’:
tandem.hpp:86:35: error: ‘cbegin’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                   ^
tandem.hpp:86:52: error: ‘cend’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                                    ^
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&, std::size_t)’:
tandem.hpp:98:31: error: ‘cbegin’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                               ^
tandem.hpp:98:48: error: ‘cend’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                                                ^
tandem.hpp: In function ‘uint32_t Tandem::detail::forward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:118:20: error: ‘std::cbegin’ has not been declared
         using std::cbegin;
                    ^
tandem.hpp: In function ‘uint32_t Tandem::detail::backward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:133:20: error: ‘std::crend’ has not been declared
         using std::crend;
                    ^
tandem.hpp: In function ‘std::vectorstd::vector<Tandem::StringRun > Tandem::detail::get_end_buckets(const T&, const std::vectorTandem::LZBlock&, uint32_t, uint32_t)’:
tandem.hpp:311:27: error: ‘cbegin’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                           ^
tandem.hpp:311:46: error: ‘cend’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                                              ^
tandem.hpp:311:71: error: ‘cend’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                                                                       ^
tandem.hpp: In function ‘std::vectorstd::vector<Tandem::StringRun > Tandem::detail::find_maximal_repetitions(const T&, uint32_t, uint32_t)’:
tandem.hpp:364:63: error: ‘cbegin’ is not a member of ‘std’
                 const auto last_target_itr = std::lower_bound(std::cbegin(target), std::cend(target), v,
                                                               ^
tandem.hpp:364:84: error: ‘cend’ is not a member of ‘std’
                 const auto last_target_itr = std::lower_bound(std::cbegin(target), std::cend(target), v,
                                                                                    ^
tandem.hpp:369:56: error: ‘cbegin’ is not a member of ‘std’
                 const auto num_targets = std::distance(std::cbegin(target), last_target_itr);
                                                        ^
tandem.hpp:374:36: error: ‘cbegin’ is not a member of ‘std’
                     std::transform(std::cbegin(target), last_target_itr, std::begin(shifted_targets),
                                    ^
tandem.hpp:379:77: error: ‘cbegin’ is not a member of ‘std’
                     sorted_buckets[j].insert(std::begin(sorted_buckets[j]), std::cbegin(shifted_targets),
                                                                             ^
tandem.hpp:380:46: error: ‘cend’ is not a member of ‘std’
                                              std::cend(shifted_targets));
                                              ^
tandem.hpp: In function ‘auto Tandem::detail::count_runs(const std::vector<_RealType>&)’:
tandem.hpp:391:32: error: ‘cbegin’ is not a member of ‘std’
         return std::accumulate(std::cbegin(buckets), std::cend(buckets), std::size_t {0},
                                ^
tandem.hpp:391:54: error: ‘cend’ is not a member of ‘std’
         return std::accumulate(std::cbegin(buckets), std::cend(buckets), std::size_t {0},
                                                      ^
tandem.hpp: In function ‘auto Tandem::detail::find_homopolymers(const T&)’:
tandem.hpp:466:34: error: ‘cbegin’ is not a member of ‘std’
         return find_homopolymers(std::cbegin(str), std::cend(str));
                                  ^
tandem.hpp:466:52: error: ‘cend’ is not a member of ‘std’
         return find_homopolymers(std::cbegin(str), std::cend(str));
                                                    ^
tandem.hpp: In function ‘auto Tandem::detail::find_exact_dinucleotide_tandem_repeats(const T&)’:
tandem.hpp:472:45: error: ‘cbegin’ is not a member of ‘std’
         return find_exact_tandem_repeats<2>(std::cbegin(str), std::cend(str));
                                             ^
tandem.hpp:472:63: error: ‘cend’ is not a member of ‘std’
         return find_exact_tandem_repeats<2>(std::cbegin(str), std::cend(str));
                                                               ^
tandem.hpp: In function ‘auto Tandem::detail::find_exact_trinucleotide_tandem_repeats(const T&)’:
tandem.hpp:478:45: error: ‘cbegin’ is not a member of ‘std’
         return find_exact_tandem_repeats<3>(std::cbegin(str), std::cend(str));
                                             ^
tandem.hpp:478:63: error: ‘cend’ is not a member of ‘std’
         return find_exact_tandem_repeats<3>(std::cbegin(str), std::cend(str));
                                                               ^
tandem.hpp: In function ‘std::vectorTandem::StringRun Tandem::find_maximal_repetitions(const T&, uint32_t, uint32_t)’:
tandem.hpp:544:41: error: ‘cbegin’ is not a member of ‘std’
         result.insert(std::end(result), std::cbegin(bucket), std::cend(bucket));
                                         ^
tandem.hpp:544:62: error: ‘cend’ is not a member of ‘std’
         result.insert(std::end(result), std::cbegin(bucket), std::cend(bucket));
                                                              ^
tandem.hpp: In function ‘std::map<long unsigned int, long unsigned int> Tandem::collapse(SequenceType&, char)’:
tandem.hpp:593:68: error: ‘cbegin’ is not a member of ‘std’
         sequence.erase(std::unique(std::next(std::begin(sequence), std::cbegin(result)->first), last,
                                                                    ^
example.cpp: In function ‘void find_big_repeats(std::string&)’:
example.cpp:49:36: error: ‘cbegin’ is not a member of ‘std’
         auto it = std::max_element(std::cbegin(repeats), std::cend(repeats),
                                    ^
example.cpp:49:58: error: ‘cend’ is not a member of ‘std’
         auto it = std::max_element(std::cbegin(repeats), std::cend(repeats),
                                                          ^
example.cpp:54:31: error: ‘cbegin’ is not a member of ‘std’
         it = std::max_element(std::cbegin(repeats), std::cend(repeats),
                               ^
example.cpp:54:53: error: ‘cend’ is not a member of ‘std’
         it = std::max_element(std::cbegin(repeats), std::cend(repeats),
                                                     ^
In file included from example.cpp:10:0:
tandem.hpp: In instantiation of ‘std::vectorTandem::StringRun Tandem::find_maximal_repetitions(const T&, uint32_t, uint32_t) [with T = std::basic_string<char>; uint32_t = unsigned int]’:
example.cpp:42:61:   required from here
tandem.hpp:513:61: error: could not convert ‘Tandem::detail::find_homopolymersstd::basic_string<char >((\* & str))’ from ‘void’ to ‘std::vectorTandem::StringRun’
                 case 1: return detail::find_homopolymers(str);
                                                             ^
tandem.hpp:514:82: error: use of ‘auto Tandem::detail::find_exact_dinucleotide_tandem_repeats(const T&) [with T = std::basic_string<char>]’ before deduction of ‘auto’
                 case 2: return detail::find_exact_dinucleotide_tandem_repeats(str);
                                                                                  ^
tandem.hpp:514:82: error: invalid use of ‘auto’
tandem.hpp:515:83: error: use of ‘auto Tandem::detail::find_exact_trinucleotide_tandem_repeats(const T&) [with T = std::basic_string<char>]’ before deduction of ‘auto’
                 case 3: return detail::find_exact_trinucleotide_tandem_repeats(str);
                                                                                   ^
tandem.hpp:515:83: error: invalid use of ‘auto’
tandem.hpp:520:56: error: ‘void result’ has incomplete type
             auto result = detail::find_homopolymers(str);
                                                        ^
tandem.hpp:522:78: error: invalid use of ‘auto’
             detail::append(detail::find_exact_dinucleotide_tandem_repeats(str), result);
                                                                              ^
tandem.hpp:525:83: error: invalid use of ‘auto’
                 detail::append(detail::find_exact_trinucleotide_tandem_repeats(str), result);
                                                                                   ^
tandem.hpp:530:77: error: invalid use of ‘auto’
             auto result = detail::find_exact_dinucleotide_tandem_repeats(str);
                                                                             ^
tandem.hpp:532:79: error: invalid use of ‘auto’
             detail::append(detail::find_exact_trinucleotide_tandem_repeats(str), result);
                                                                               ^
tandem.hpp:541:53: error: use of ‘auto Tandem::detail::count_runs(const std::vector<_RealType>&) [with T = std::vectorTandem::StringRun]’ before deduction of ‘auto’
     result.reserve(detail::count_runs(sorted_buckets));
                                                     ^
tandem.hpp:541:53: error: invalid use of ‘auto’
In file included from tandem.cpp:25:0:
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&)’:
tandem.hpp:86:35: error: ‘cbegin’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                   ^
tandem.hpp:86:52: error: ‘cend’ is not a member of ‘std’
     return std::vector<uint32_t> {std::cbegin(sa), std::cend(sa)};
                                                    ^
tandem.hpp: In function ‘std::vector<unsigned int> Tandem::make_suffix_array(const T&, std::size_t)’:
tandem.hpp:98:31: error: ‘cbegin’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                               ^
tandem.hpp:98:48: error: ‘cend’ is not a member of ‘std’
     const auto it = std::copy(std::cbegin(sa), std::cend(sa), std::begin(result));
                                                ^
tandem.hpp: In function ‘uint32_t Tandem::detail::forward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:118:20: error: ‘std::cbegin’ has not been declared
         using std::cbegin;
                    ^
tandem.hpp: In function ‘uint32_t Tandem::detail::backward_lce(const T&, uint32_t, uint32_t, uint32_t)’:
tandem.hpp:133:20: error: ‘std::crend’ has not been declared
         using std::crend;
                    ^
tandem.hpp: In function ‘std::vectorstd::vector<Tandem::StringRun > Tandem::detail::get_end_buckets(const T&, const std::vectorTandem::LZBlock&, uint32_t, uint32_t)’:
tandem.hpp:311:27: error: ‘cbegin’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                           ^
tandem.hpp:311:46: error: ‘cend’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                                              ^
tandem.hpp:311:71: error: ‘cend’ is not a member of ‘std’
             if (std::find(std::cbegin(curr), std::cend(curr), run) == std::cend(curr)) {
                                                                       ^
tandem.hpp: In function ‘std::vectorstd::vector<Tandem::StringRun > Tandem::detail::find_maximal_repetitions(const T&, uint32_t, uint32_t)’:
tandem.hpp:364:63: error: ‘cbegin’ is not a member of ‘std’
                 const auto last_target_itr = std::lower_bound(std::cbegin(target), std::cend(target), v,
                                                               ^
tandem.hpp:364:84: error: ‘cend’ is not a member of ‘std’
                 const auto last_target_itr = std::lower_bound(std::cbegin(target), std::cend(target), v,
                                                                                    ^
tandem.hpp:369:56: error: ‘cbegin’ is not a member of ‘std’
                 const auto num_targets = std::distance(std::cbegin(target), last_target_itr);
                                                        ^
tandem.hpp:374:36: error: ‘cbegin’ is not a member of ‘std’
                     std::transform(std::cbegin(target), last_target_itr, std::begin(shifted_targets),
                                    ^
tandem.hpp:379:77: error: ‘cbegin’ is not a member of ‘std’
                     sorted_buckets[j].insert(std::begin(sorted_buckets[j]), std::cbegin(shifted_targets),
                                                                             ^
tandem.hpp:380:46: error: ‘cend’ is not a member of ‘std’
                                              std::cend(shifted_targets));
                                              ^
tandem.hpp: In function ‘auto Tandem::detail::count_runs(const std::vector<_RealType>&)’:
tandem.hpp:391:32: error: ‘cbegin’ is not a member of ‘std’
         return std::accumulate(std::cbegin(buckets), std::cend(buckets), std::size_t {0},
                                ^
tandem.hpp:391:54: error: ‘cend’ is not a member of ‘std’
         return std::accumulate(std::cbegin(buckets), std::cend(buckets), std::size_t {0},
                                                      ^
tandem.hpp: In function ‘auto Tandem::detail::find_homopolymers(const T&)’:
tandem.hpp:466:34: error: ‘cbegin’ is not a member of ‘std’
         return find_homopolymers(std::cbegin(str), std::cend(str));
                                  ^
tandem.hpp:466:52: error: ‘cend’ is not a member of ‘std’
         return find_homopolymers(std::cbegin(str), std::cend(str));
                                                    ^
tandem.hpp: In function ‘auto Tandem::detail::find_exact_dinucleotide_tandem_repeats(const T&)’:
tandem.hpp:472:45: error: ‘cbegin’ is not a member of ‘std’
         return find_exact_tandem_repeats<2>(std::cbegin(str), std::cend(str));
                                             ^
tandem.hpp:472:63: error: ‘cend’ is not a member of ‘std’
         return find_exact_tandem_repeats<2>(std::cbegin(str), std::cend(str));
                                                               ^
tandem.hpp: In function ‘auto Tandem::detail::find_exact_trinucleotide_tandem_repeats(const T&)’:
tandem.hpp:478:45: error: ‘cbegin’ is not a member of ‘std’
         return find_exact_tandem_repeats<3>(std::cbegin(str), std::cend(str));
                                             ^
tandem.hpp:478:63: error: ‘cend’ is not a member of ‘std’
         return find_exact_tandem_repeats<3>(std::cbegin(str), std::cend(str));
                                                               ^
tandem.hpp: In function ‘std::vectorTandem::StringRun Tandem::find_maximal_repetitions(const T&, uint32_t, uint32_t)’:
tandem.hpp:544:41: error: ‘cbegin’ is not a member of ‘std’
         result.insert(std::end(result), std::cbegin(bucket), std::cend(bucket));
                                         ^
tandem.hpp:544:62: error: ‘cend’ is not a member of ‘std’
         result.insert(std::end(result), std::cbegin(bucket), std::cend(bucket));
                                                              ^
tandem.hpp: In function ‘std::map<long unsigned int, long unsigned int> Tandem::collapse(SequenceType&, char)’:
tandem.hpp:593:68: error: ‘cbegin’ is not a member of ‘std’
         sequence.erase(std::unique(std::next(std::begin(sequence), std::cbegin(result)->first), last,
                                                                    ^
tandem.cpp: In function ‘void Tandem::rebase(std::vectorTandem::StringRun&, const std::map<long unsigned int, long unsigned int>&)’:
tandem.cpp:175:25: error: ‘cbegin’ is not a member of ‘std’
     auto shift_map_it = std::cbegin(shift_map);
                         ^
tandem.cpp:178:43: error: ‘cend’ is not a member of ‘std’
         while (std::next(shift_map_it) != std::cend(shift_map) && std::next(shift_map_it)->first <= run.pos) {
                                           ^
In file included from libdivsufsort/divsufsort_private.h:80:0,
                 from libdivsufsort/utils.c:27:
libdivsufsort/utils.c: In function ‘saint_t sufcheck(const sauchar_t_, const saidx_t_, saidx_t, saint_t)’:
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:183:49: note: in expansion of macro ‘PRIdSAIDX_T’
         fprintf(stderr, "Out of the range [0,%" PRIdSAIDX_T "].\n"
                                                 ^
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:196:36: note: in expansion of macro ‘PRIdSAIDX_T’
                         "  T[SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T "]=%d"
                                    ^
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:227:34: note: in expansion of macro ‘PRIdSAIDX_T’
                         "  SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T " or\n"
                                  ^
make: **\* [all] Error 1

**Comment by dancooke** [comment]
Ah, this one **is** because you need C++14.

**Comment by lmanchon** [comment]
yes, this is what i thought.
C++14 is not available on my computing cluster, only compiler gcc-4.9.1.
Is it easy to make a version with C++11 compatibility ?

thank you --
