### ISSUE TITLE
gcc 6.1.10

### ISSUE THREAD

**Issue by lmanchon** [dancooke/tandem#3]
--Hi,

sorry again me,
i have installed gcc 6.1.10 which support -std=c++14 parameter:

gcc --version
gcc (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

the comiplation again failed with:

g++ example.cpp tandem.cpp libdivsufsort/divsufsort.c libdivsufsort/sssort.c libdivsufsort/trsort.c libdivsufsort/utils.c -w -std=c++14 -O3 -o tandem
In file included from libdivsufsort/divsufsort_private.h:80:0,
                 from libdivsufsort/utils.c:27:
libdivsufsort/utils.c: In function ‘saint_t sufcheck(const sauchar_t_, const saidx_t_, saidx_t, saint_t)’:
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:183:49: note: in expansion of macro ‘PRIdSAIDX_T’
         fprintf(stderr, "Out of the range [0,%" PRIdSAIDX_T "].\n"
                                                 ^~~~~~~~~~~
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:196:36: note: in expansion of macro ‘PRIdSAIDX_T’
                         "  T[SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T "]=%d"
                                    ^~~~~~~~~~~
libdivsufsort/divsufsort.h:53:21: error: expected ‘)’ before ‘PRId32’
 #define PRIdSAIDX_T PRId32
                     ^
libdivsufsort/utils.c:227:34: note: in expansion of macro ‘PRIdSAIDX_T’
                         "  SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T " or\n"
                                  ^~~~~~~~~~~
make: **\* [all] Error 1

Laurent --

**Comment by dancooke** [comment]
Looks like a problem with gcc; I'm not getting this error with Clang. Anyway, I've removed all the `printf`s from libdivsufsort, which seems to be causing the error. Can you try again please with the update?

**Comment by lmanchon** [comment]
ok, it compile fine now.
it's strange i have already used libdivsufsort library with another tool and i don't remember any problem in compilation.
so, problem is over.
thank you.
